apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infomaniak-api-token
  namespace: cert-manager
spec:
  data:
  - remoteRef:
      key: e455a6c8-fe47-4e3c-85e2-b388015864cf
    secretKey: api-token
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager

