---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: helm-sources
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.20.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: helm-sources
  install:
    createNamespace: true
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
    bitwarden-sdk-server:
      enabled: true

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.cert-manager.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.cert-manager.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: kik-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: 8c53bfa5-0d3d-43e8-890b-b0260148d1ee
      projectID: 9d1d5cf9-92cf-4701-8e44-b35900d2388e

