---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets

  ---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: helm-sources
spec:
  interval: 1m0s
  url: https://charts.external-secrets.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 5m
  chart:
    spec:
      chart: external-secrets
      version: 0.20.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: helm-sources
  install:
    createNamespace: true
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
    bitwarden-sdk-server:
      enabled: true

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
  namespace: external-secrets
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.cert-manager.svc.cluster.local
    - external-secrets-bitwarden-sdk-server.cert-manager.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: kik-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io

