---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: helm-sources
spec:
  interval: 5m0s
  type: "oci"
  url: oci://quay.io/jetstack/charts/cert-manager

